### PR TITLE
Bug/lc-reject-future-dates

### LINKED ISSUE #118: Update last contacted to reject future dates
should only accept dates in the past/ the present date

Image

### PR DESCRIPTION
**Pull request by nicho369**
LastContactedDate will reject future dates - based on SG timezone
fixes #118 

image

### CODE REVIEW

File: src/main/java/seedu/address/model/person/LastContactedDate.java [hunk 1]
```diff
@@ -13,12 +14,15 @@
  */
 public class LastContactedDate {
     public static final String MESSAGE_CONSTRAINTS =
-            "Last contacted date should be in YYYY-MM-DD format (e.g., 2025-09-20) "
-            + "and should be a valid calendar date.";
+            "Last contacted date should be in YYYY-MM-DD format (e.g., 2025-09-20), "
+            + "should be a valid calendar date, and cannot be a future date.";
```
Comment (cyfake) [inline src/main/java/seedu/address/model/person/LastContactedDate.java]: Good catch!

**Review by cyfake — APPROVED** [review]
LGTM!
