### PR TITLE
Bug fix empty occupation

### LINKED ISSUE #112: Change handling for when no Occupation is given
Image
No occupation given, but engineer given

### PR DESCRIPTION
**Pull request by ChengLeong**
fixes #112

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddCommandParser.java [hunk 1]
```diff
@@ -66,7 +66,7 @@ public AddCommand parse(String args) throws ParseException {
                 argMultimap.getValue(PREFIX_PRIORITY).orElse(Priority.Level.NONE.toString()));
         Occupation occupation = argMultimap.getValue(PREFIX_OCCUPATION).isPresent()
                 ? ParserUtil.parseOccupation(argMultimap.getValue(PREFIX_OCCUPATION).get())
-                : new Occupation("Engineer");
+                : new Occupation("");
```
Comment (lanjia0) [inline src/main/java/seedu/address/logic/parser/AddCommandParser.java]: Good job changing the default Occupation from engineer to a null input that will not be displayed

**Review by lanjia0 — APPROVED** [review]
Overall looks good to me
