### PR TITLE
Fix edit to allow duplicate names

### LINKED ISSUE #191: Fix duplicate check for names
We need to allow for the use case when two contacts have the same name but different phone number.

Right now, the edit command does not allow to users to have the same name but different number.

Change the behaviour of the edit command to allow this.

### PR DESCRIPTION
**Pull request by zpnoob**
Fixes #191

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 1]
```diff
@@ -148,8 +149,6 @@ private void checkForDuplicates(Model model, Person personToEdit, Person editedP
 
         if (hasNameConflict && hasPhoneConflict) {
             throw new CommandException(MESSAGE_DUPLICATE_NAME_AND_PHONE);
-        } else if (hasNameConflict) {
```
Comment (cyfake) [inline src/main/java/seedu/address/logic/commands/EditCommand.java]: Good catch that the name field should allow duplicates
