### PR TITLE
Bug/command result message no income field even with income added

### LINKED ISSUE #125: Income bracket does not show in command result message when adding a new contact with income value

### PR DESCRIPTION
**Pull request by zpnoob**
Fixes #125

### CODE REVIEW

File: src/main/java/seedu/address/logic/Messages.java [hunk 1]
```diff
@@ -52,6 +52,9 @@ public static String format(Person person) {
         if (!person.getAddress().toString().isEmpty()) {
             builder.append("; Address: ").append(person.getAddress());
         }
+        if (person.getIncomeBracket() != null) {
+            builder.append("; Income Bracket: ").append(person.getIncomeBracket().getValue());
```
Comment (cyfake) [inline src/main/java/seedu/address/logic/Messages.java]: Good catch! Good job adding this case
